openapi: 3.0.3
info:
  title: Robot service 3.0
  description: API сервис управления роботом - пылесосом.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
servers:
- url: https://localhost:9669
tags:
- name: User
  description: Контроллер пользователя.
- name: Schedule
  description: Контроллер расписания.
- name: Group
  description: Контроллер группы.
- name: Robot
  description: Контроллер робота.
paths:
  /User:
    post:
      tags:
      - User
      summary: Добавить пользователя
      description: Добавить пользователя в базу
      operationId: add_user
      requestBody:
        description: Создание нового пользователя в базе
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
          application/xml:
            schema:
              $ref: '#/components/schemas/User'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
            application/xml:
              schema:
                $ref: '#/components/schemas/User'
        "405":
          description: Invalid input
      x-openapi-router-controller: swagger_server.controllers.user_controller
  /User/UpdateById/{userId}:
    put:
      tags:
      - User
      summary: обновляет информацию о пользователе по ID
      description: обновляет информацию о пользователе
      operationId: update_user
      parameters:
      - name: userId
        in: path
        description: Идентификатор пользователя
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
            application/xml:
              schema:
                $ref: '#/components/schemas/User'
        "400":
          description: Invalid ID supplied
        "404":
          description: User not found
      x-openapi-router-controller: swagger_server.controllers.user_controller
  /User/findById/{userId}:
    get:
      tags:
      - User
      summary: Найти пользователя по ID
      description: вернуть одного пользователя
      operationId: get_user_by_id
      parameters:
      - name: userId
        in: path
        description: Идентификатор пользователя
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
            application/xml:
              schema:
                $ref: '#/components/schemas/User'
        "400":
          description: Invalid ID supplied
        "404":
          description: User not found
      x-openapi-router-controller: swagger_server.controllers.user_controller
  /User/deleteById/{userId}:
    delete:
      tags:
      - User
      summary: Удаляет пользователя
      description: Удаляет пользователя
      operationId: delete_user
      parameters:
      - name: userId
        in: header
        description: ""
        required: false
        style: simple
        explode: false
        schema:
          type: string
      - name: userId
        in: path
        description: ID пользователя
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "400":
          description: Invalid User value
      x-openapi-router-controller: swagger_server.controllers.user_controller
  /Group:
    put:
      tags:
      - Group
      summary: Обновить группу
      description: Обновить группу
      operationId: update_group
      requestBody:
        description: Обновить существующую группу в базе
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Group'
          application/xml:
            schema:
              $ref: '#/components/schemas/Group'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Group'
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Group'
            application/xml:
              schema:
                $ref: '#/components/schemas/Group'
        "400":
          description: Invalid ID supplied
        "404":
          description: Group not found
        "405":
          description: Validation exception
      x-openapi-router-controller: swagger_server.controllers.group_controller
    post:
      tags:
      - Group
      summary: Добавить группу
      description: Добавить группу в базу
      operationId: add_group
      requestBody:
        description: Создание новой группы в базе
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Group'
          application/xml:
            schema:
              $ref: '#/components/schemas/Group'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Group'
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Group'
            application/xml:
              schema:
                $ref: '#/components/schemas/Group'
        "405":
          description: Invalid input
      x-openapi-router-controller: swagger_server.controllers.group_controller
  /Group/findById/{groupId}:
    get:
      tags:
      - Group
      summary: Найти группу по ID
      description: вернуть группу
      operationId: get_group_by_id
      parameters:
      - name: groupId
        in: path
        description: Идентификатор группы
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Group'
            application/xml:
              schema:
                $ref: '#/components/schemas/Group'
        "400":
          description: Invalid ID supplied
        "404":
          description: Group not found
      x-openapi-router-controller: swagger_server.controllers.group_controller
  /Group/deleteById/{groupId}:
    delete:
      tags:
      - Group
      summary: Удаляет пользователя
      description: Удаляет пользователя
      operationId: delete_group
      parameters:
      - name: groupId
        in: header
        description: ""
        required: false
        style: simple
        explode: false
        schema:
          type: string
      - name: groupId
        in: path
        description: ID пользователя
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "400":
          description: Invalid Group value
      x-openapi-router-controller: swagger_server.controllers.group_controller
  /Robot:
    put:
      tags:
      - Robot
      summary: Обновить робота
      description: Обновить робота
      operationId: update_robot
      requestBody:
        description: Обновить существующего робота в базе
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Robot'
          application/xml:
            schema:
              $ref: '#/components/schemas/Robot'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Robot'
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Robot'
            application/xml:
              schema:
                $ref: '#/components/schemas/Robot'
        "400":
          description: Invalid ID supplied
        "404":
          description: Robot not found
        "405":
          description: Validation exception
      x-openapi-router-controller: swagger_server.controllers.robot_controller
    post:
      tags:
      - Robot
      summary: Добавить робота
      description: Добавить робота в базу
      operationId: add_robot
      requestBody:
        description: Создание нового робота в базе
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Robot'
          application/xml:
            schema:
              $ref: '#/components/schemas/Robot'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Robot'
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Robot'
            application/xml:
              schema:
                $ref: '#/components/schemas/Robot'
        "405":
          description: Invalid input
      x-openapi-router-controller: swagger_server.controllers.robot_controller
  /Robot/findById/{robotId}:
    get:
      tags:
      - Robot
      summary: Найти робота по ID
      description: вернуть робота
      operationId: get_robot_by_id
      parameters:
      - name: robotId
        in: path
        description: Идентификатор робота
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Robot'
            application/xml:
              schema:
                $ref: '#/components/schemas/Robot'
        "400":
          description: Invalid ID supplied
        "404":
          description: Robot not found
      x-openapi-router-controller: swagger_server.controllers.robot_controller
  /Robot/deleteById/{robotId}:
    delete:
      tags:
      - Robot
      summary: Удаляет робота
      description: Удаляет робота
      operationId: delete_robot
      parameters:
      - name: robotId
        in: header
        description: ""
        required: false
        style: simple
        explode: false
        schema:
          type: string
      - name: robotId
        in: path
        description: ID робота
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "400":
          description: Invalid Robot value
      x-openapi-router-controller: swagger_server.controllers.robot_controller
  /Schedule:
    put:
      tags:
      - Schedule
      summary: Обновить расписание
      description: Обновить расписание
      operationId: update_schedule
      requestBody:
        description: Обновить существующее расписание в базе
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Schedule'
          application/xml:
            schema:
              $ref: '#/components/schemas/Schedule'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Schedule'
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Schedule'
            application/xml:
              schema:
                $ref: '#/components/schemas/Schedule'
        "400":
          description: Invalid ID supplied
        "404":
          description: Schedule not found
        "405":
          description: Validation exception
      x-openapi-router-controller: swagger_server.controllers.schedule_controller
    post:
      tags:
      - Schedule
      summary: Добавить расписание
      description: Добавить расписание в базу
      operationId: add_schedule
      requestBody:
        description: Создать новое расписание в базе
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Schedule'
          application/xml:
            schema:
              $ref: '#/components/schemas/Schedule'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Schedule'
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Schedule'
            application/xml:
              schema:
                $ref: '#/components/schemas/Schedule'
        "405":
          description: Invalid input
      x-openapi-router-controller: swagger_server.controllers.schedule_controller
  /Schedule/findById/{scheduleId}:
    get:
      tags:
      - Schedule
      summary: Найти расписание по ID
      description: вернуть одно расписание
      operationId: get_schedule_by_id
      parameters:
      - name: scheduleId
        in: path
        description: Идентификатор расписания
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Schedule'
            application/xml:
              schema:
                $ref: '#/components/schemas/Schedule'
        "400":
          description: Invalid ID supplied
        "404":
          description: Schedule not found
      x-openapi-router-controller: swagger_server.controllers.schedule_controller
  /Schedule/deleteById/{scheduleId}:
    delete:
      tags:
      - Schedule
      summary: Удалить расписание по ID
      description: Удаляет расписание
      operationId: delete_schedule_by_id
      parameters:
      - name: scheduleId
        in: header
        description: Идентификатор расписания
        required: false
        style: simple
        explode: false
        schema:
          type: string
      - name: scheduleId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Schedule'
            application/xml:
              schema:
                $ref: '#/components/schemas/Schedule'
        "400":
          description: Invalid ID supplied
        "404":
          description: Schedule not found
      x-openapi-router-controller: swagger_server.controllers.schedule_controller
components:
  schemas:
    User:
      required:
      - email
      - passHash
      - robotSNHash
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        email:
          type: string
          example: somemail@mail.ru
        passHash:
          type: integer
          format: int64
          example: 23412
        robotSNHash:
          type: integer
          format: int64
          example: 23412
      example:
        robotSNHash: 23412
        id: 10
        passHash: 23412
        email: somemail@mail.ru
      xml:
        name: pet
    Group:
      required:
      - userId
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        userId:
          type: integer
          format: int64
          example: 10
      example:
        id: 10
        userId: 10
      xml:
        name: Group
    Schedule:
      required:
      - dateTime
      - mode
      - robotId
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        dateTime:
          type: string
          example: dd.mm.yyyy-hh:mm:ss
        mode:
          type: integer
          format: int64
          example: 10
        robotId:
          type: integer
          format: int64
          example: 10
      example:
        dateTime: dd.mm.yyyy-hh:mm:ss
        mode: 10
        id: 10
        robotId: 10
      xml:
        name: Schedule
    Robot:
      required:
      - charge
      - garbageContainer
      - groupId
      - ipAddress
      - model
      - nextService
      - robotContamination
      - serialNumber
      - version
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        model:
          type: string
          example: something
        version:
          type: string
          example: something
        charge:
          type: integer
          format: int64
          example: 10
        garbageContainer:
          type: integer
          format: int64
          example: 10
        robotContamination:
          type: integer
          format: int64
          example: 10
        nextService:
          type: integer
          format: int64
          example: 10
        serialNumber:
          type: string
          example: something
        ipAddress:
          type: integer
          format: int64
          example: 10
        groupId:
          type: integer
          format: int64
          example: 10
      example:
        charge: 10
        serialNumber: something
        nextService: 10
        groupId: 10
        ipAddress: 10
        model: something
        id: 10
        robotContamination: 10
        garbageContainer: 10
        version: something
      xml:
        name: Robot
  requestBodies:
    User:
      description: Данные пользователя
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/User'
        application/xml:
          schema:
            $ref: '#/components/schemas/User'
    UserArray:
      description: Список пользователей
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/User'
    Group:
      description: Данные группы
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Group'
        application/xml:
          schema:
            $ref: '#/components/schemas/Group'
    GroupArray:
      description: Список групп
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Group'
    Robot:
      description: Данные группы
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Robot'
        application/xml:
          schema:
            $ref: '#/components/schemas/Robot'
    RobotArray:
      description: Список групп
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Robot'
    Schedule:
      description: Данные группы
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Schedule'
        application/xml:
          schema:
            $ref: '#/components/schemas/Schedule'
    ScheduleArray:
      description: Список групп
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Schedule'

